<a href="https://colab.research.google.com/github/Teferihagos/Datasciencecoursera/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a tuple
my_tuple = (6, 7, 8, 9, 10)

# Printing the list and tuple
print("List:", my_list)
print("Tuple:", my_tuple)

 #using python

List: [1, 2, 3, 4, 5]
Tuple: (6, 7, 8, 9, 10)


In [ ]:
import numpy as np

# Creating a NumPy array from a list
my_numpy_array_from_list = np.array([1, 2, 3, 4, 5])

# Creating a NumPy array from a tuple
my_numpy_array_from_tuple = np.array((6, 7, 8, 9, 10))

# Printing the NumPy arrays
print("NumPy Array from List:", my_numpy_array_from_list)
print("NumPy Array from Tuple:", my_numpy_array_from_tuple)

 #using numpy

NumPy Array from List: [1 2 3 4 5]
NumPy Array from Tuple: [ 6  7  8  9 10]


In [ ]:
import numpy as np

# Creating a NumPy array from a list
my_numpy_array_from_list = np.array([1, 2, 3, 4, 5])

# Creating a NumPy array from a tuple
my_numpy_array_from_tuple = np.array((6, 7, 8, 9, 10))

# Printing the NumPy arrays
print("NumPy Array from List:", my_numpy_array_from_list)
print("NumPy Array from Tuple:", my_numpy_array_from_tuple)

 #using numpy



[1, 2, 3, 4, 5]


In [ ]:
#1.Array Indexing:


# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements by index
element_at_index_0 = my_array[0]  # Access the first element
element_at_index_3 = my_array[3]  # Access the fourth element

print("Element at index 0:", element_at_index_0)
print("Element at index 3:", element_at_index_3)


#2.Array Slicing:


# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Basic slicing
slice_1 = my_array[1:4]  # Elements from index 1 to 3
slice_2 = my_array[:3]   # Elements from the beginning to index 2
slice_3 = my_array[2:]   # Elements from index 2 to the end

print("Slice 1:", slice_1)
print("Slice 2:", slice_2)
print("Slice 3:", slice_3)

# Slicing with step
slice_with_step = my_array[::2]  # Elements with a step of 2
print("Slice with step:", slice_with_step)

#3. Negative Indices and Reverse Slicing:

import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Negative indexing
element_at_index_minus_1 = my_array[-1]  # Access the last element
element_at_index_minus_2 = my_array[-2]  # Access the second-to-last element

print("Element at index -1:", element_at_index_minus_1)
print("Element at index -2:", element_at_index_minus_2)

# Reverse slicing
reverse_slice = my_array[::-1]  # Reverse the array
print("Reverse Slice:", reverse_slice)




Element at index 0: 1
Element at index 3: 4
Slice 1: [2 3 4]
Slice 2: [1 2 3]
Slice 3: [3 4 5]
Slice with step: [1 3 5]
Element at index -1: 5
Element at index -2: 4
Reverse Slice: [5 4 3 2 1]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_add = arr1 + arr2  # [5, 7, 9]

# Subtraction
result_sub = arr1 - arr2  # [-3, -3, -3]

# Multiplication
result_mul = arr1 * arr2  # [4, 10, 18]

# Division
result_div = arr1 / arr2  # [0.25, 0.4, 0.5]

#result_add
#result_sub
#result_div
#result_mul


In [ ]:
arr = np.array([1, 2, 3])

# Square root
result_sqrt = np.sqrt(arr)  # [1.0, 1.41421356, 1.73205081]



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Mean
mean = np.mean(arr)  # 3.0

# Sum
sum_val = np.sum(arr)  # 15

# Minimum
min_val = np.min(arr)  # 1

# Maximum
max_val = np.max(arr)  # 5

max_val

5

In [ ]:
#Broadcasting

import numpy as np

# Create a 2x3 array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1x3 array
B = np.array([10, 20, 30])

# Adding the arrays with different shapes using broadcasting
result = A + B

# Broadcasting automatically expands B to match the shape of A
# Resulting in the following operation:
# [[1+10, 2+20, 3+30],
#  [4+10, 5+20, 6+30]]

print(result)


[[11 22 33]
 [14 25 36]]


In [ ]:
#Reshaping Arrays:

arr = np.arange(12)  # Create a 1D array with values from 0 to 11 you can't add 14 for example because you can't multiply 3*4 != 14
reshaped_arr = arr.reshape((3, 4))  # Reshape it into a 3x4 2D array
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#ravel(): It flattens a multi-dimensional array into a 1D array. This operation doesn't create a new array but returns a flattened view of the original array.

flat_arr = reshaped_arr.ravel()
flat_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
resized_arr = np.resize(arr, (3, 2))
resized_arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
#Changing Data Type

float_arr = arr.astype(float)  # Convert to a float data type
float_arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
#transpose(): This method allows you to transpose the dimensions of an array.
transposed_arr = arr.T  # Transpose a 2D array
transposed_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
swapped_arr = arr.swapaxes(0, 1) #resized_arr  # Swap the first and second axes
swapped_arr

AxisError: ignored

In [ ]:
#Reading Data using numpy:

# Load data from a CSV file into a NumPy array
data = np.genfromtxt('Test_data.csv', delimiter=',', dtype=float)

# 'data.csv' is a CSV file with comma-separated values. You can specify the delimiter accordingly.
# The 'dtype' parameter specifies the desired data type for the loaded data.

#Reading Data using numpy:

# Load data from a binary file (NumPy .npy format)
data = np.load('data.npy')

# 'data.npy' is a binary file previously saved using np.save()

In [ ]:
#Writing to a Text File (e.g., CSV):

# Create a NumPy array
data = np.array([[1, 2, 3], [4, 5, 6]])
# Save the data to a CSV file
np.savetxt('output.csv', data, delimiter=',', fmt='%d')

# 'output.csv' will contain the data in CSV format. The 'fmt' parameter specifies the format for each element.




In NumPy's np.savetxt function, the fmt parameter specifies the format for each element in the array when saving data to a text file (e.g., CSV). The fmt parameter allows you to control how the data is represented in the output file, including the number of decimal places, scientific notation, and more.

Here's how the fmt parameter works:

If fmt is a string:

It specifies a single format for all elements in the array.
For example, fmt='%d' specifies that all elements should be formatted as integers, and fmt='%.2f' specifies that all elements should be formatted as floating-point numbers with two decimal places.
If fmt is a sequence (e.g., a list or tuple):

It allows you to specify a different format for each column in the array.
The length of the sequence should match the number of columns in the array.
For example, if you have a 2D array with two columns and you want the first column as integers and the second column as floating-point numbers with two decimal places, you can use fmt=('%d', '%.2f').
Here are some common format codes you can use with the fmt parameter:

%d: Integer format
%f: Floating-point format
%.nf: Floating-point format with n decimal places (e.g., %.2f for two decimal places)
%e or %E: Scientific notation with lowercase or uppercase 'e' (e.g., %e for lowercase, %E for uppercase)

The delimiter parameter is used when saving data to a text file (e.g., CSV) or when reading data from a text file in NumPy. It specifies the character or sequence of characters that separates values in the text file. The delimiter helps NumPy understand how to split the data into individual elements or columns.

Here's how the delimiter parameter works:

When saving data to a text file:

You specify the delimiter to indicate how the values in the NumPy array should be separated in the output file. Common delimiters include commas, spaces, tabs, semicolons, or any other character or sequence of characters.
For example, delimiter=',' specifies that values should be separated by commas, while delimiter='\t' specifies tab-separated values.
When reading data from a text file:

You specify the delimiter when using functions like np.genfromtxt to tell NumPy how to split the values in the input text file into individual elements in the resulting NumPy array.
NumPy will split the lines in the text file at occurrences of the specified delimiter, creating columns from the separated values.

In [ ]:
# writing on a binary file

# Create a NumPy array
data = np.array([1, 2, 3, 4, 5])

# Save the data to a binary file (NumPy .npy format)
np.save('output.npy', data)

# 'output.npy' will contain the data in binary format, which can be loaded later using np.load()